name: AI Code Review
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr-agent:
    if: ${{ ! contains(github.event.*.labels.*.name, 'ignore-for-ai-code-review') && github.event.sender.type != 'Bot' }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese.'
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese.'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'Please use Japanese.'
          github_action.auto_describe: "true"
          github_action.auto_review: "true"
          github_action.auto_improve: "true"
          pr_description.publish_labels: "false"
          pr_reviewer.enable_review_labels_security: "false"
          pr_reviewer.enable_review_labels_effort: "false"
